### PR TITLE
Add support for local files with file:// schema.

### PR DESCRIPTION
**Pull request by GrzegorzDrozd**
Using local file vs content of a file ( for parse method ) allows one to use recursive parsing or queue parsing approach and just replace url with local file. Easier for dev time and testing. I also added a test that creates local file in temp.

### CODE REVIEW

**Comment by JanPetterMG** [comment]
Thanks, havent tested it yet, but I'll do it as soon as possible (within a day or two). Merge and new version will be released shortly after, assuming everything goes according to the plan. Stay tuned.

**Comment by JanPetterMG** [comment]
There seems to be an code conflict between the PRs, could you take a look at this @GrzegorzDrozd ? Thanks.

**Comment by GrzegorzDrozd** [comment]
> There seems to be an code conflict between the PRs, could you take a look at this @GrzegorzDrozd ? Thanks.

Done.

**Comment by JanPetterMG** [comment]
Version [1.2.0](https://github.com/VIPnytt/SitemapParser/releases/tag/v1.2.0) is now released.
Thank you @GrzegorzDrozd

**Pull request merged**
